import type { Currency, Settings } from "./types";

/** Fiat currencies offered in the popup picker (ISO 4217). */
export const currencies: Currency[] = [
	{ code: "AED", name: "UAE Dirham" },
	{ code: "AFN", name: "Afghan Afghani" },
	{ code: "ALL", name: "Albanian Lek" },
	{ code: "AMD", name: "Armenian Dram" },
	{ code: "ANG", name: "Netherlands Antillean Guilder" },
	{ code: "AOA", name: "Angolan Kwanza" },
	{ code: "ARS", name: "Argentine Peso" },
	{ code: "AUD", name: "Australian Dollar" },
	{ code: "AWG", name: "Aruban Florin" },
	{ code: "AZN", name: "Azerbaijani Manat" },
	{ code: "BAM", name: "Bosnia-Herzegovina Convertible Mark" },
	{ code: "BBD", name: "Barbadian Dollar" },
	{ code: "BDT", name: "Bangladeshi Taka" },
	{ code: "BGN", name: "Bulgarian Lev" },
	{ code: "BHD", name: "Bahraini Dinar" },
	{ code: "BIF", name: "Burundian Franc" },
	{ code: "BMD", name: "Bermudan Dollar" },
	{ code: "BND", name: "Brunei Dollar" },
	{ code: "BOB", name: "Bolivian Boliviano" },
	{ code: "BRL", name: "Brazilian Real" },
	{ code: "BSD", name: "Bahamian Dollar" },
	{ code: "BTN", name: "Bhutanese Ngultrum" },
	{ code: "BWP", name: "Botswanan Pula" },
	{ code: "BYN", name: "Belarusian Ruble" },
	{ code: "BZD", name: "Belize Dollar" },
	{ code: "CAD", name: "Canadian Dollar" },
	{ code: "CDF", name: "Congolese Franc" },
	{ code: "CHF", name: "Swiss Franc" },
	{ code: "CLP", name: "Chilean Peso" },
	{ code: "CNY", name: "Chinese Yuan" },
	{ code: "CNH", name: "Chinese Yuan (offshore)" },
	{ code: "COP", name: "Colombian Peso" },
	{ code: "CRC", name: "Costa Rican Colón" },
	{ code: "CUP", name: "Cuban Peso" },
	{ code: "CVE", name: "Cape Verdean Escudo" },
	{ code: "CZK", name: "Czech Koruna" },
	{ code: "DJF", name: "Djiboutian Franc" },
	{ code: "DKK", name: "Danish Krone" },
	{ code: "DOP", name: "Dominican Peso" },
	{ code: "DZD", name: "Algerian Dinar" },
	{ code: "EGP", name: "Egyptian Pound" },
	{ code: "ERN", name: "Eritrean Nakfa" },
	{ code: "ETB", name: "Ethiopian Birr" },
	{ code: "EUR", name: "Euro" },
	{ code: "FJD", name: "Fijian Dollar" },
	{ code: "FKP", name: "Falkland Islands Pound" },
	{ code: "GBP", name: "British Pound" },
	{ code: "GEL", name: "Georgian Lari" },
	{ code: "GHS", name: "Ghanaian Cedi" },
	{ code: "GGP", name: "Guernsey Pound" },
	{ code: "GIP", name: "Gibraltar Pound" },
	{ code: "GMD", name: "Gambian Dalasi" },
	{ code: "GNF", name: "Guinean Franc" },
	{ code: "GTQ", name: "Guatemalan Quetzal" },
	{ code: "GYD", name: "Guyanaese Dollar" },
	{ code: "HKD", name: "Hong Kong Dollar" },
	{ code: "HNL", name: "Honduran Lempira" },
	{ code: "HTG", name: "Haitian Gourde" },
	{ code: "HUF", name: "Hungarian Forint" },
	{ code: "IDR", name: "Indonesian Rupiah" },
	{ code: "ILS", name: "Israeli New Shekel" },
	{ code: "IMP", name: "Isle of Man Pound" },
	{ code: "INR", name: "Indian Rupee" },
	{ code: "IQD", name: "Iraqi Dinar" },
	{ code: "IRR", name: "Iranian Rial" },
	{ code: "ISK", name: "Icelandic Króna" },
	{ code: "JMD", name: "Jamaican Dollar" },
	{ code: "JEP", name: "Jersey Pound" },
	{ code: "JOD", name: "Jordanian Dinar" },
	{ code: "JPY", name: "Japanese Yen" },
	{ code: "KES", name: "Kenyan Shilling" },
	{ code: "KGS", name: "Kyrgystani Som" },
	{ code: "KHR", name: "Cambodian Riel" },
	{ code: "KMF", name: "Comorian Franc" },
	{ code: "KPW", name: "North Korean Won" },
	{ code: "KRW", name: "South Korean Won" },
	{ code: "KWD", name: "Kuwaiti Dinar" },
	{ code: "KYD", name: "Cayman Islands Dollar" },
	{ code: "KZT", name: "Kazakhstani Tenge" },
	{ code: "LAK", name: "Laotian Kip" },
	{ code: "LBP", name: "Lebanese Pound" },
	{ code: "LKR", name: "Sri Lankan Rupee" },
	{ code: "LRD", name: "Liberian Dollar" },
	{ code: "LSL", name: "Lesotho Loti" },
	{ code: "LYD", name: "Libyan Dinar" },
	{ code: "MAD", name: "Moroccan Dirham" },
	{ code: "MDL", name: "Moldovan Leu" },
	{ code: "MGA", name: "Malagasy Ariary" },
	{ code: "MKD", name: "Macedonian Denar" },
	{ code: "MMK", name: "Myanmar Kyat" },
	{ code: "MNT", name: "Mongolian Tugrik" },
	{ code: "MOP", name: "Macanese Pataca" },
	{ code: "MRU", name: "Mauritanian Ouguiya" },
	{ code: "MUR", name: "Mauritian Rupee" },
	{ code: "MVR", name: "Maldivian Rufiyaa" },
	{ code: "MWK", name: "Malawian Kwacha" },
	{ code: "MXN", name: "Mexican Peso" },
	{ code: "MYR", name: "Malaysian Ringgit" },
	{ code: "MZN", name: "Mozambican Metical" },
	{ code: "NAD", name: "Namibian Dollar" },
	{ code: "NGN", name: "Nigerian Naira" },
	{ code: "NIO", name: "Nicaraguan Córdoba" },
	{ code: "NOK", name: "Norwegian Krone" },
	{ code: "NPR", name: "Nepalese Rupee" },
	{ code: "NZD", name: "New Zealand Dollar" },
	{ code: "OMR", name: "Omani Rial" },
	{ code: "PAB", name: "Panamanian Balboa" },
	{ code: "PEN", name: "Peruvian Sol" },
	{ code: "PGK", name: "Papua New Guinean Kina" },
	{ code: "PHP", name: "Philippine Peso" },
	{ code: "PKR", name: "Pakistani Rupee" },
	{ code: "PLN", name: "Polish Złoty" },
	{ code: "PYG", name: "Paraguayan Guaraní" },
	{ code: "QAR", name: "Qatari Riyal" },
	{ code: "RON", name: "Romanian Leu" },
	{ code: "RSD", name: "Serbian Dinar" },
	{ code: "RUB", name: "Russian Ruble" },
	{ code: "RWF", name: "Rwandan Franc" },
	{ code: "SAR", name: "Saudi Riyal" },
	{ code: "SBD", name: "Solomon Islands Dollar" },
	{ code: "SCR", name: "Seychellois Rupee" },
	{ code: "SDG", name: "Sudanese Pound" },
	{ code: "SEK", name: "Swedish Krona" },
	{ code: "SGD", name: "Singapore Dollar" },
	{ code: "SHP", name: "Saint Helena Pound" },
	{ code: "SLE", name: "Sierra Leonean Leone" },
	{ code: "SOS", name: "Somali Shilling" },
	{ code: "SRD", name: "Surinamese Dollar" },
	{ code: "SSP", name: "South Sudanese Pound" },
	{ code: "STN", name: "São Tomé and Príncipe Dobra" },
	{ code: "SYP", name: "Syrian Pound" },
	{ code: "SZL", name: "Swazi Lilangeni" },
	{ code: "THB", name: "Thai Baht" },
	{ code: "TJS", name: "Tajikistani Somoni" },
	{ code: "TMT", name: "Turkmenistani Manat" },
	{ code: "TND", name: "Tunisian Dinar" },
	{ code: "TOP", name: "Tongan Paʻanga" },
	{ code: "TRY", name: "Turkish Lira" },
	{ code: "TVD", name: "Tuvaluan Dollar" },
	{ code: "TTD", name: "Trinidad and Tobago Dollar" },
	{ code: "TWD", name: "New Taiwan Dollar" },
	{ code: "TZS", name: "Tanzanian Shilling" },
	{ code: "UAH", name: "Ukrainian Hryvnia" },
	{ code: "UGX", name: "Ugandan Shilling" },
	{ code: "USD", name: "US Dollar" },
	{ code: "UYU", name: "Uruguayan Peso" },
	{ code: "UZS", name: "Uzbekistani Som" },
	{ code: "VES", name: "Venezuelan Bolívar" },
	{ code: "VND", name: "Vietnamese Dong" },
	{ code: "VUV", name: "Vanuatu Vatu" },
	{ code: "WST", name: "Samoan Tala" },
	{ code: "XAF", name: "Central African CFA Franc" },
	{ code: "XCD", name: "East Caribbean Dollar" },
	{ code: "XOF", name: "West African CFA Franc" },
	{ code: "XPF", name: "CFP Franc" },
	{ code: "YER", name: "Yemeni Rial" },
	{ code: "ZAR", name: "South African Rand" },
	{ code: "ZMW", name: "Zambian Kwacha" },
	{ code: "ZWG", name: "Zimbabwean Gold" },
];

/**
 * Symbol token -> ISO code. Ambiguous symbols map to the most common reading
 * and can be overridden by the user. A `null` value means "not convertible on
 * its own": it needs an accompanying ISO code.
 */
export const symbolToCode: Record<string, string | null> = {
	US$: "USD",
	R$: "BRL",
	C$: "CAD",
	A$: "AUD",
	NZ$: "NZD",
	S$: "SGD",
	HK$: "HKD",
	NT$: "TWD",
	MX$: "MXN",
	$: "USD",
	"€": "EUR",
	"£": "GBP",
	"¥": "JPY",
	"₩": "KRW",
	"₹": "INR",
	"₽": "RUB",
	"₺": "TRY",
	"₪": "ILS",
	"₴": "UAH",
	"₦": "NGN",
	"₱": "PHP",
	"฿": "THB",
	"₫": "VND",
	"₡": "CRC",
	"₲": "PYG",
	"₸": "KZT",
	"₨": "PKR",
	"৳": "BDT",
	"₾": "GEL",
	"₼": "AZN",
	"₵": "GHS",
	"﷼": "SAR",
	zł: "PLN",
	Kč: "CZK",
	Ft: "HUF",
	lei: "RON",
	лв: "BGN",
	дин: "RSD",
	ден: "MKD",
	դր: "AMD",
	KSh: "KES",
	RM: "MYR",
	Rp: "IDR",
	"S/": "PEN",
	DH: "MAD",
	"E£": "EGP",
	// Ambiguous by nature: unresolved unless the user pins them or the TLD hints.
	kr: null,
	R: null,
	Rs: null,
	L: null,
};

/**
 * Ambiguous symbols resolved by the site's top-level domain, e.g. `kr` is
 * DKK on .dk, SEK on .se, NOK on .no.
 */
export const symbolTldHints: Record<string, Record<string, string>> = {
	kr: { dk: "DKK", se: "SEK", no: "NOK", is: "ISK", fo: "DKK", gl: "DKK" },
	Rs: { in: "INR", pk: "PKR", lk: "LKR", np: "NPR" },
	R: { za: "ZAR" },
	L: { al: "ALL", md: "MDL" },
};

/** All recognised ISO codes (explicit markers for detection). */
export const codes: string[] = currencies.map((c) => c.code);

export const defaultSettings: Settings = {
	enabled: true,
	targetCurrency: "USD",
	locale: "",
	displayMode: "inline",
	abbreviateLarge: false,
	symbolOverrides: {},
	excludedHosts: [],
};
